#ifndef COMPONENT_H
#define COMPONENT_H

#include "id_types.h"

typedef enum {
    COMPONENT_TYPE_SPRITE,
    COMPONENT_TYPE_POSITION,
    COMPONENT_TYPE_CLICKABLE
} COMPONENT_TYPE;

#endif // COMPONENT_H
