blank_issues_enabled: false
contact_links:
  - name: Workflow Documentation
    url: https://github.com/o92design/raylib_svea/blob/master/DEVELOPMENT_PLAN.md#workflow
    about: Read our documentation for more information.
issue_template: feature.md