name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: sudo apt-get install -y build-essential libraylib-dev libcunit1-dev

    - name: Build project
      run: make ci-build

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: sudo apt-get install -y build-essential libraylib-dev libcunit1-dev

    - name: Run tests
      run: make ci-test

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: sudo apt-get install -y clang-tidy

    - name: Lint code
      run: clang-tidy src/**/*.c include/**/*.h -- -Iinclude -Ilib
